name: CI

on:
  push:
  pull_request:
    branches: [develop]

jobs:
  usage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install colorama
        python -m pip install tomli
        pip freeze

    - name: logview default configuration
      run: |
        # No configuration file.
        # The archive is from tmarktaylor/pytest-phmdoctest
        python logview.py tests/archives/logs_19.zip
